(require racket/tcp)
(define (server)
    (define listener1 (tcp-listen 5001))
    (define listener2 (tcp-listen 5002))
    (define-values (in out) (tcp-accept listener1))
    (define-values (in2 out2) (tcp-accept listener2))
    (let ciclo ()
        (define msg)
    )
)